### ISSUE TITLE
Marlin 1.1.9

### ISSUE THREAD

**Issue by doby77** [fieldOfView/Cura-LinearAdvanceSettingPlugin#1]
Depuis Marlin 1.1.9 le facteur K à changé si je rentre 0.35 ça me fait un k0 dans mon start gcode.

New K value required

As the unit of K has changed, you have to redo the K calibration procedure. See next chapter for details. While old v1 K values for PLA might be between 30-130, you can now expect K to be around 0.1-2.0.

http://marlinfw.org/docs/features/lin_advance.html#special-notes-for-v1.5

**Comment by fieldOfView** [comment]
I think you forgot to translate the first line. Fortunately, I know just about enough french to spot my mistake in the code; the 3.5.0 version of the plugin rounds float values to integer.

**Comment by fieldOfView** [comment]
Fixed here: 97bed8d138c5f15534fbf8e6d02f2df8b0c6d488
I will publish a new version of the plugin. Until that is available, you can manually add the M900 command to your start gcode snippet (in Machine Settings):

```
...
M900 K{material_linear_advance_factor}
...
```
The setting you entered in the sidebar will be inserted automatically then (keeping the decimals).
