### ISSUE TITLE
Question: Maximum allowed value

### ISSUE THREAD

**Issue by Noguai** [fieldOfView/Cura-LinearAdvanceSettingPlugin#14]
I have seen that your Plugin, which is very useful by the way, thanks very much for your work, got an update and noticed while looking for changes that with commit 51fd5617c950d5e28eef34e878298229462db88c the maximum allowed value of the linear advance setting has, as I understand it, been changed from a warning at 2 without maximum to a maximum of 10. 

Could you please revert that change? Some users among us are stuck with linear advance 1.0 and would need to enter larger values.

I haven't updated yet in fear of breaking my existing print profiles...

**Comment by fieldOfView** [comment]
I set the maximum allowed value to 10 because Marlin 1.1.9 and newer throw an exception ("crash") if the value is higher than 10. But I can see how this is problematic for older versions of Marlin.
