### ISSUE TITLE
Can't Set Linear Advance to 0

### ISSUE THREAD

**Issue by gayuha** [fieldOfView/Cura-LinearAdvanceSettingPlugin#16]
When I set the option to 0, it does not add the command to the gcode. The printer then uses the previously set value, instead of disabling linear advance.

**Comment by fieldOfView** [comment]
Fair enough, I'll get this fixed.

**Comment by fieldOfView** [comment]
Fixed in https://github.com/fieldOfView/Cura-LinearAdvanceSettingPlugin/commit/b42ca9fa29ab3ba46b37ab0d1eabe3c385eb4d2c
