### ISSUE TITLE
M900 command not added to start gcode

### ISSUE THREAD

**Issue by Peshtigost** [fieldOfView/Cura-LinearAdvanceSettingPlugin#17]
![la1](https://user-images.githubusercontent.com/61399812/75127385-795c8600-5684-11ea-9ec3-f097b1a702d4.PNG)
Installed the Linear Advance Plugin in Cura 3.6.0 (I would use 4.anything if they would work on my computer-  see numerous error logs sent).  When I set a value of anything greater than zero, say .5 for example and check the start code I see no M900 command added.  Without the M900  command entering a value has no effect on printing.
![la2](https://user-images.githubusercontent.com/61399812/75127393-7d88a380-5684-11ea-9b42-1b8f6ac233d9.PNG)
![la3](https://user-images.githubusercontent.com/61399812/75127398-811c2a80-5684-11ea-8e9e-0c5428903783.PNG)

**Comment by fieldOfView** [comment]
The M900 commands will be inserted into the saved gcode, but they will not appear in the Start G-code snippet in the Machine Settings. Please save a gcode file to disk, inspect the resulting file with eg notepad, and you should see the expected M900 command there.

> (I would use 4.anything if they would work on my computer- see numerous error logs sent)

I have no access to those logs. I am not an Ultimaker employee; I'm a community member who writes plugins.
