### ISSUE TITLE
Issue with Comma

### ISSUE THREAD

**Issue by DavidEnduro** [fieldOfView/Cura-LinearAdvanceSettingPlugin#2]
Hey ;)

There are no comma numbers taken over. 
for example 0.4 
I need that for Linear Advance> v1.5

Thanks in advance.

Greets David

**Comment by fieldOfView** [comment]
Ho (-;

Duplicate of #1 
I will post an updated version to the Toolbox

**Comment by DavidEnduro** [comment]
Thanks ;)! 

Great Work!

**Comment by fieldOfView** [comment]
The fixed version is not available in the ~Toolbox~Marketplace
