### ISSUE TITLE
%d format: a number is required, not str

### ISSUE THREAD

**Issue by fieldOfView** [fieldOfView/Cura-LinearAdvanceSettingPlugin#23]
@fieldOfView this plugin broke saving file or print via octorpint for a long time. 
![image](https://user-images.githubusercontent.com/10683722/89762763-c250ab80-daf9-11ea-8e0c-e94d2802a8cf.png)

I use this plugin with a fix:
```py
gcode_command_pattern = "M900 K%f T%s"
```

_Originally posted by @dankatanka in https://github.com/Ultimaker/Cura/issues/8156#issuecomment-671218312_

**Comment by WhiskeyTang0F0xtr0t** [comment]
I installed this plugin today and I'm having this issue with my X-Max. I'm assuming it's because it's not supported or in the wrong format. It adds extra steps to the workflow to enable this for my creality printers, disable, restart, send to X-Max, re-enable, restart, etc.
