### ISSUE TITLE
Make a filament-specific field in the material manager to adjust this setting 

### ISSUE THREAD

**Issue by carlosg-gh** [fieldOfView/Cura-LinearAdvanceSettingPlugin#24]
While I find this extension really useful since I don't need to tool with the firmware to change the linear advance, I think that it would be a great idea to add a field in the filament manager to store each filament specific K-value for the linear advance, and use that one automatically unless a different K-value is defined in the slicer.

Just to be sure I'm explaining myself, this is the menu I'm talking about.

![image](https://user-images.githubusercontent.com/13695988/92621830-a0973f80-f2c4-11ea-9c79-78b3c0c7e0ea.png)

I believe both Cura and this plugin would benefit a lot from this feature, since the K-value can differ between spools of the same material and even the same brand, but the value remains mostly consistent in the same spool.

I may look to add this myself, but I'm not familiar with Cura plugins so I'd love to know the feasibility of making this a feature.

**Comment by fieldOfView** [comment]
It looks like you are already using the Material Settings plugin. With Extensions -> Material Settings -> Configure Material Settings, you can select which settings are shown in the Print settings tab of the material preferences.

**Comment by carlosg-gh** [comment]
Oh, I didn't know that this was a thing. Thanks and sorry for bothering you!
