### ISSUE TITLE
HELP: Combined infills / adapted Linear advance

### ISSUE THREAD

**Issue by studiodyne** [fieldOfView/Cura-LinearAdvanceSettingPlugin#29]
**When using  combined infills ,  for ex : Outlines in 0.1mm in 4 passes , and Infills in 0.4mm in one pass  (for gain of time )**

An issue appears , the machine doesn't have the ' linear advance setting for the 0.4mm layer height ' and  each lines in 0.4 are shorter , don't overlap , and infills are SHIT ! . If i use only one linear advance setting , either i have big corners or i have unglued infills... Linear Advance not ' really linear in vertical mode 😄', because depending of the nozzle size, layer height , direct drive or bowden , solid filament or flexible , two many parameters in the equation 😢  

IDEA 
Add a gcode comment like this  ' Current layer height = xxxx ' in the flavor , and it's all
Every time CURA change the layer height  , the machine receive the information 

I don't want LA 
I don't want to use LA in cura
I HAVE IT in the machine

I just want CURA send the information to the machine when changing printing strategy 

Thks

ps: I will make a PR in MarlinFirmware to apply the right LA , but i need the slicer HELP ME !

**Comment by fieldOfView** [comment]
< Add a gcode comment like this ' Current layer height = xxxx ' in the flavor , and it's all

That is not something this plugin can help you with.
