### ISSUE TITLE
Feature request : K-factor setting in material menu

### ISSUE THREAD

**Issue by atsju** [fieldOfView/Cura-LinearAdvanceSettingPlugin#30]
The K factor depends only of material and printer. Many people may have only 1 printer so it may be a good option to save the factor with the material. Changing material could then automatically change the K same as it does for plate and nozzle temperature.

People with several printers may duplicate the material for each printer that requires different K.

**Comment by fieldOfView** [comment]
This can be achieved with the Material Settings plugin.

**Comment by fieldOfView** [comment]
See https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MaterialSettingsPlugin
