### ISSUE TITLE
Turn off Linear Advance for some printers

### ISSUE THREAD

**Issue by AndreasALu** [fieldOfView/Cura-LinearAdvanceSettingPlugin#32]
Hi!

I have several different printers configurated in Cura, some of them do not support Linear Advance, some do. If I install the plugin, it puts a M572 or M900 in every G-code file, which causes the printers that do not support LA to throw an error.

I tried to do a post-processing via Search&Replace, but it seems that the LA plugin runs after the Post Processing Plugin, therefor I cannot get rid of the unwanted command.

The Post Processing steps are saved per printer, so it would normally work.

Is there a way to deactivate the plugin per printer oder at least run the plugin before the Post Processing Plugin?

**Comment by fieldOfView** [comment]
There currently is no way to deactivate the plugin for a certain printer. Thanks for the request, this is on my shortlist of things to fix for the next version of the plugin.

**Comment by AndreasALu** [comment]
Thx for the quick reply. Would it be easier to run the LA plugin *before* the post processing plugin? That would solve my problem.

**Comment by fieldOfView** [comment]
It would not solve mine ;-)

**Comment by tutulino** [comment]
Same problem here, I have multiple printers and I usually use firmware configured Linear Advance, but some profiles I need different linear advance (for example 0.8 nozzle, or different materials) I think best way to solve all problems is add a check box at profile level to activate/deactivate linear advance control, same way Cura does for Jerk or acceleration.

This way you can install plugin and use for some printer or some profiles only

**Comment by Mbytes** [comment]
Hello, fix not work, send gcode M900

If value it's 0, not print in gcode command M900

I possible??

Thanks.
