### ISSUE TITLE
No new line before M900

### ISSUE THREAD

**Issue by blazewicz** [fieldOfView/Cura-LinearAdvanceSettingPlugin#33]
### Context

Cura: v4.9.1
Plugin: v3.5.11

### Description

Below is fragment of generated G-code, just after the start G-code:

```gcode
G92 E0
G92 E0
G1 F2700 E-5
;LAYER_COUNT:100M900 K0.750000 T0 ;added by LinearAdvanceSettingPlugin

;LAYER:0
M107
```

A newline is missing after `;LAYER_COUNT:100`.

**Comment by fieldOfView** [comment]
Strange. Can you save a project (File -> Save project...) so I can see what combination of settings leads to this?

**Comment by blazewicz** [comment]
Sure, I can't share it on GitHub so I emailed you.

**Comment by blazewicz** [comment]
Sorry for false alert, it was my script adding M117 with current progress that mangled the output. Your plugin works fine when I disabled it.
