### ISSUE TITLE
Allow to set LA value on material presets

### ISSUE THREAD

**Issue by knoopx** [fieldOfView/Cura-LinearAdvanceSettingPlugin#4]
It would be nice if the field shows in the material preset print settings dialog:

![image](https://user-images.githubusercontent.com/100993/51614815-c1135a00-1f26-11e9-9e91-39b63297ab61.png)

**Comment by fieldOfView** [comment]
I agree that would be nice, but it is outside the scope of what this plugin can do.

**Comment by fieldOfView** [comment]
I have created a plugin that lets the user select which print settings are available on the Materials pane of the preferences. It is still a bit rough, but an initial version can be downloaded here:

Cura 3.5/3.6: http://files.fieldofview.com/cura/MaterialSettingsPlugin-v5.0.0-2019-04-27T19_48_03Z.curapackage
Cura 4.0: http://files.fieldofview.com/cura/MaterialSettingsPlugin-v6.0.0-2019-04-27T19_48_03Z.curapackage

After downloading, just drop the file into a running Cura window, and restart Cura when requested. By default, the plugin adds the Flow setting to the Print Settings tab of materials on the Materials pane of the preferences.

The plugin also adds a dialog to configure additional settings to be included in the material Print Settings, see Extensions -> Material Settings -> Configure Material Settings. Using that dialog it is possible to add other settings such as Z Offset or Linear Advance Factor if you have the respective plugins for that installed.

Feedback is appreciated.
