### ISSUE TITLE
Not compatible with Cura 5.0

### ISSUE THREAD

**Issue by qwertymodo** [fieldOfView/Cura-LinearAdvanceSettingPlugin#41]
Upon upgrading to 5.0, Cura notified me that this plugin was not compatible and required reinstallation, however it doesn't appear to be available for installation in the marketplace either, so it seems this plugin needs to be updated for compatibility with Cura 5.0.

**Comment by fieldOfView** [comment]
See https://community.ultimaker.com/topic/40313-fieldofview-plugins-for-cura-50/ for a prerelease version to test.

A version of the plugin is in review for release on the Marketplace.

**Comment by qwertymodo** [comment]
Awesome, glad to hear it. I noticed a bunch of your other plugins were already updated, this was just the one I couldn't find.
