### ISSUE TITLE
Bug: Cura refuses to save gcode twice in a row

### ISSUE THREAD

**Issue by DruckiMcDruck** [fieldOfView/Cura-LinearAdvanceSettingPlugin#7]
I tinkered with this little plugin to add other features. While doing so i encountered a possible bug: As long as this plugin is enabled, i can't save gcode twice in a row without (re-)slicing it.

How to reproduce:
1. Add plugin to Cura 3.6.0
2. Slice object
3. save gode to drive for the first time (this will work)
4. try to save gcode again to drive (this won't work till cura slices again, the file simply isn't written to disk)

I expected to be able to save as many times as i wanted to without having to slice again by changing a random setting in Cura. Here's the error log i got:

https://gist.github.com/DruckiMcDruck/11675a2a1fdccd853dc236017e651da9

**Comment by fieldOfView** [comment]
Well spotted, will fix.
