### ISSUE TITLE
Custom Plugin with more than one setting

### ISSUE THREAD

**Issue by TheTiEr** [fieldOfView/Cura-LinearAdvanceSettingPlugin#8]
Hey, 

i hope you are able to help me and I am at the right place.

I have to write my own plugin and i am trying to own settings with some subsettings to the settings container. I am able to add one setting, like you did in this plugin.

But I need more than one setting and need the option to enable and disable this plugin in the Print Settings.

```
self._setting_dict = {
            "label": "Enable my special plugin with childs",
            "description": "Enbales my special plugin!",
            "type": "bool",
            "default_value": 0,
            "settable_per_mesh": False,
            "settable_per_extruder": False,
            "settable_per_meshgroup": False,
            "children":
            {
            "experimental_my_plugin_float_setting":
                {
                    "label": "Diameter",
                    "description": "Adjusts the diameter of the filament used. Match this value with the diameter of the used filament.",
                    "unit": "mm",
                    "type": "float",
                    "default_value": 2.85,
                    "minimum_value": "0.0001",
                    "minimum_value_warning": "0.4",
                    "maximum_value_warning": "3.5",
                    "settable_per_mesh": False,
                    "settable_per_extruder": True
                }
            }
        }
```
 
I added a "children" to the dict like it is in the FDMPrinter.json.def

The "Setting Visibility" shows the childs, but they are not shown in the Print settings. 

You can download my test plugin here: https://drive.google.com/drive/folders/15o8DGH0I47gQZc3c8LiP2Wh-YlmXRimc?usp=sharing

Greetings 
Timo

**Comment by fieldOfView** [comment]
> i hope (...) I am at the right place.

You are not in the right place. This is an issue-queue for a specific plugin, not a generic help forum.
Having said that, I have never tried adding child settings this way. Adding a setting like I do in this plugin is not officially supported and "hacky". I think you may have to add the settings one at a time, one as a child of the category, and one as a child of the first setting you added.
