### ISSUE TITLE
Can't disable linear advance (set 0) in 3.5.5

### ISSUE THREAD

**Issue by MatkovIvan** [fieldOfView/Cura-LinearAdvanceSettingPlugin#9]
`0` is valid value, but isn't allowed anymore.
![image](https://user-images.githubusercontent.com/1836384/60540603-39711900-9d18-11e9-9f31-ee9c01fa9489.png)
![image](https://user-images.githubusercontent.com/1836384/60540610-3fff9080-9d18-11e9-9565-d9717a7abd5a.png)

Please fix minimal value:
https://github.com/fieldOfView/Cura-LinearAdvanceSettingPlugin/blob/1cc2732d308d84df2ef846bc5acef79d1232bedc/LinearAdvanceSettingPlugin.py#L27

**Comment by fieldOfView** [comment]
Sorry, my thought was you would set the linear advance factor to 1 to disable it. It seems I was mistaken. I'll submit a fixed version of the plugin.

**Comment by fieldOfView** [comment]
The fixed version is now available in the Marketplace.

**Comment by MatkovIvan** [comment]
Yeah, thanks.

Fortunately, it's distributed as sources, so I was able to fix it locally.
